parser: babel-eslint
env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - airbnb
  - prettier
plugins:
  - react
  - jsx-a11y
  - import
  - prettier
rules:
  prettier/prettier: error
  func-names: error
  jsx-a11y/href-no-hash: off
  react/jsx-filename-extension: off
  react/require-default-props: off
  import/extensions:
  - error
  - json: ignorePackages
  import/no-extraneous-dependencies:
  - error
  - packageDir: "./package.json"
globals:
  jsdom: true